Mae 57984
vhl/action-combinator pull request #2
Opened 2021-09-17 20:58 UTC by mwulfvhl

2021-09-20 14:38 UTC, alboyadjian commented on .eslintrc.js
> +  'rules': {
how about pulling the non-vue-related rule overrides from m3's eslint file in app/javascript/ ?

2021-09-20 14:53 UTC, alboyadjian requested changes

2021-09-20 14:53 UTC, alboyadjian commented on src/collections.js
> + * @param {action} action An action.
2 things here
1: only js primitives should be initial  lower-case
string, number, null, undefined, boolean, etc.
2: is an action an instance of an Action class? If not, what is its type? If it can vary, or is an object with predictable properties, then you should define or import an Action typedef.

2021-09-20 14:53 UTC, alboyadjian commented on src/collections.js
> + * as any one of the actions resolves.
for jsdoc comments, the first line shouldn't have any text, just the opening comment with an extra asterisk
```suggestion
/** 
 * Create an action that runs several actions at once and resolves as soon
 * as any one of the actions resolves.
```

2021-09-20 14:53 UTC, alboyadjian commented on src/collections.js
> + * @return {action}      An action.
The extra space might confuse the automatic documentation generators. 
```suggestion
 * @return {action} An action
```

2021-09-20 14:53 UTC, alboyadjian commented on src/collections.js
> + * @param {action} action An action.
style: Separate the description from the argument name using a dash
```suggestion
 * @param {action} action - An action.
```

2021-09-20 14:53 UTC, alboyadjian commented on src/collections.js
> + * @param {action} arguments - Any of _n_ actions to be run concurrently.
The name doesn't match the actual argument used (args). Also for a repeatable param, use ...
See https://jsdoc.app/tags-param.html#multiple-types-and-repeatable-parameters
```suggestion
 * @param {...action} args - Any of _n_ actions to be run concurrently.
```

2021-09-20 14:53 UTC, alboyadjian commented on src/control_structures.js
> + * @param {function} predicate  A function that returns either true or
style (applies several times in this file):
`function` isn't a primitive so it should have initial caps. Also a dash between the name and description
```suggestion
 * @param {Function} predicate - A function that returns either true or
```

2021-09-20 14:53 UTC, alboyadjian commented on src/timing.js
> + * @param {Number} duration The amount of time, in milliseconds, to wait
```suggestion
 * @param {number} duration - The amount of time, in milliseconds, to wait
```

2021-09-20 14:53 UTC, alboyadjian commented on src/timing.js
> + * @param {Number} duration The amount of time, in milliseconds, to wait
```suggestion
 * @param {number} duration - The amount of time, in milliseconds, to wait
```

2021-09-20 14:53 UTC, alboyadjian commented on spec/core_spec.js
> +    /* eslint-disable indent */
What doesn't eslint like here if you don't include this?

2021-09-20 14:56 UTC, jrichards-vhl commented on package.json
> +    "@babel/plugin-transform-runtime": "^7.15.0",
non-blocking:

I'm not sure how many of these are necessary.  Nothing blocking, it just might increase the bundle size larger than it needs to be due to unnecessary polyfilling.

2021-09-20 16:02 UTC, mwulfvhl commented on spec/core_spec.js
> +    /* eslint-disable indent */
It expects the level of indentation within the anonymous function to be 4 spaces instead of 2.

2021-09-22 19:10 UTC, mwulfvhl commented on package.json
> +    "@babel/plugin-transform-runtime": "^7.15.0",
Good catch. I can try removing them all and seeing what breaks when I run the specs and/or the build.

2021-09-22 20:28 UTC, jrichards-vhl commented on spec/collections_spec.js
> +          myDecrementBy(4), // 8 - 4
Does this spec need specs?  (joking)

In all seriousness though, why is this necessary?

2021-09-22 20:40 UTC, jrichards-vhl approved these changes
Looks good to me overall.  I noticed that it generated a .d.ts fie, which is great!

Should we use this eslint config as a base?  I'm working on something very similar, so if I can copy/paste some of the configs, all the better.

Re-browser testing:  There are certainly ways we can do this.  When I do POCs, I'll typically run a node Express server on port 3003 (and turn off Submissions), which has addressed all of my needs so far.

Here's the little node sandbox I put together if you want to take a look:
https://github.com/jrichards-vhl/node-sandbox

And here's the entirety of the server code... seriously:
```javascript
const express = require('express');
const app = express();
const port = 3003;

app.use(express.static('public'));

app.get('/', (req, res) => {
  res.sendFile('./public/index.html', { root: __dirname });
});

app.listen(port, () => {
  console.log(`Listening on port ${port}`);
});
```

Just an idea.

2021-09-22 20:53 UTC, alboyadjian approved these changes

2021-09-22 21:28 UTC, mwulfvhl commented on spec/collections_spec.js
> +          myDecrementBy(4), // 8 - 4
Although I didn't write the spec, I think I see why it's designed this way. If the function were implemented incorrectly so that it resolved before all the actions were done, it might bail before `container` gets incremented by 2 at the end.

2021-09-23 16:33 UTC, merged